-- Manual Database Update Script
-- Run this SQL script to add confirmation_preferences table

-- 1. Create confirmation_preferences table
CREATE TABLE IF NOT EXISTS "confirmation_preferences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "confirmation_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"target_user_id" bigint NOT NULL,
	"require_debt_creation" boolean DEFAULT true,
	"require_debt_payment" boolean DEFAULT true,
	"require_debt_deletion" boolean DEFAULT true,
	"require_debt_completion" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);

-- 2. Add unique constraint
ALTER TABLE "confirmation_preferences" 
ADD CONSTRAINT "confirmation_preferences_user_id_target_user_id_unique" 
UNIQUE("user_id","target_user_id");

-- 3. Add foreign key constraints
ALTER TABLE "confirmation_preferences" 
ADD CONSTRAINT "confirmation_preferences_user_id_tg_users_id_fk" 
FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "confirmation_preferences" 
ADD CONSTRAINT "confirmation_preferences_target_user_id_tg_users_id_fk" 
FOREIGN KEY ("target_user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;

-- 4. Create indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_confirmation_prefs_user_id" ON "confirmation_preferences"("user_id");
CREATE INDEX IF NOT EXISTS "idx_confirmation_prefs_target_user_id" ON "confirmation_preferences"("target_user_id");

-- 5. Verify the table was created successfully
SELECT 
    column_name, 
    data_type, 
    is_nullable, 
    column_default
FROM information_schema.columns 
WHERE table_name = 'confirmation_preferences' 
ORDER BY ordinal_position;

-- 6. Check constraints
SELECT 
    constraint_name, 
    constraint_type
FROM information_schema.table_constraints 
WHERE table_name = 'confirmation_preferences';

-- Success message
SELECT 'confirmation_preferences table created successfully!' as status;