CREATE TABLE "action_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "action_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint,
	"group_id" bigint,
	"action_type" text,
	"payload" jsonb,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chat_messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"session_id" bigint,
	"sender" text NOT NULL,
	"sender_tg_id" bigint,
	"message_text" text NOT NULL,
	"delay_ms" integer,
	"intent" text,
	"sql_query" text,
	"sql_params" jsonb,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chat_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" bigint,
	"user_id" bigint,
	"started_at" timestamp DEFAULT now(),
	"last_activity" timestamp DEFAULT now(),
	"context_hash" text,
	"active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "food_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "food_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"category" text,
	"region" text,
	"image_url" text,
	"source_url" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "name_aliases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "name_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"owner_user_id" bigint NOT NULL,
	"alias_text" text NOT NULL,
	"ref_user_id" bigint,
	"confidence" numeric(3, 2) DEFAULT '0',
	"last_used" timestamp DEFAULT now(),
	CONSTRAINT "name_aliases_owner_user_id_alias_text_unique" UNIQUE("owner_user_id","alias_text")
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"debt_id" bigint,
	"payer_id" bigint,
	"amount" numeric(14, 2) NOT NULL,
	"paid_at" timestamp DEFAULT now(),
	"note" text
);
--> statement-breakpoint
CREATE TABLE "pending_confirmations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pending_confirmations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"debt_id" bigint NOT NULL,
	"action_type" text NOT NULL,
	"requested_by" bigint NOT NULL,
	"lender_confirmed" boolean DEFAULT false,
	"borrower_confirmed" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"expires_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "tg_group_members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tg_group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" bigint,
	"user_id" bigint,
	"joined_at" timestamp DEFAULT now(),
	"nickname_in_group" text,
	"last_seen" timestamp DEFAULT now(),
	CONSTRAINT "tg_group_members_group_id_user_id_unique" UNIQUE("group_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "tg_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tg_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tg_chat_id" bigint NOT NULL,
	"title" text,
	"type" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "tg_groups_tg_chat_id_unique" UNIQUE("tg_chat_id")
);
--> statement-breakpoint
CREATE TABLE "tg_users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tg_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tg_id" bigint NOT NULL,
	"tg_username" text,
	"display_name" text,
	"real_name" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "tg_users_tg_id_unique" UNIQUE("tg_id")
);
--> statement-breakpoint
ALTER TABLE "ai_conversations" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bot_memories" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bot_moods" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_members" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversation_messages" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversation_summaries" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "debt_records" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "ai_conversations" CASCADE;--> statement-breakpoint
DROP TABLE "bot_memories" CASCADE;--> statement-breakpoint
DROP TABLE "bot_moods" CASCADE;--> statement-breakpoint
DROP TABLE "chat_members" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_messages" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_summaries" CASCADE;--> statement-breakpoint
DROP TABLE "debt_records" CASCADE;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "debts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "amount" SET DATA TYPE numeric(14, 2);--> statement-breakpoint
ALTER TABLE "food_suggestions" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "food_suggestions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "food_suggestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "food_suggestions" ALTER COLUMN "user_id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "food_suggestions" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "group_id" bigint;--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "lender_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "borrower_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "note" text;--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "occurred_at" timestamp DEFAULT now();--> statement-breakpoint
ALTER TABLE "debts" ADD COLUMN "settled" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD COLUMN "group_id" bigint;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD COLUMN "food_id" bigint;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD COLUMN "query" text;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD COLUMN "suggested_at" timestamp DEFAULT now();--> statement-breakpoint
ALTER TABLE "action_logs" ADD CONSTRAINT "action_logs_user_id_tg_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "action_logs" ADD CONSTRAINT "action_logs_group_id_tg_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."tg_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_session_id_chat_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."chat_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_group_id_tg_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."tg_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_user_id_tg_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "name_aliases" ADD CONSTRAINT "name_aliases_owner_user_id_tg_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "name_aliases" ADD CONSTRAINT "name_aliases_ref_user_id_tg_users_id_fk" FOREIGN KEY ("ref_user_id") REFERENCES "public"."tg_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_debt_id_debts_id_fk" FOREIGN KEY ("debt_id") REFERENCES "public"."debts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_payer_id_tg_users_id_fk" FOREIGN KEY ("payer_id") REFERENCES "public"."tg_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pending_confirmations" ADD CONSTRAINT "pending_confirmations_debt_id_debts_id_fk" FOREIGN KEY ("debt_id") REFERENCES "public"."debts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pending_confirmations" ADD CONSTRAINT "pending_confirmations_requested_by_tg_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."tg_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tg_group_members" ADD CONSTRAINT "tg_group_members_group_id_tg_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."tg_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tg_group_members" ADD CONSTRAINT "tg_group_members_user_id_tg_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debts" ADD CONSTRAINT "debts_group_id_tg_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."tg_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debts" ADD CONSTRAINT "debts_lender_id_tg_users_id_fk" FOREIGN KEY ("lender_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debts" ADD CONSTRAINT "debts_borrower_id_tg_users_id_fk" FOREIGN KEY ("borrower_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD CONSTRAINT "food_suggestions_user_id_tg_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD CONSTRAINT "food_suggestions_group_id_tg_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."tg_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "food_suggestions" ADD CONSTRAINT "food_suggestions_food_id_food_items_id_fk" FOREIGN KEY ("food_id") REFERENCES "public"."food_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "debtor_user_id";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "debtor_username";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "creditor_user_id";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "creditor_username";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "description";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "is_paid";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "paid_at";--> statement-breakpoint
ALTER TABLE "debts" DROP COLUMN "ai_detection";--> statement-breakpoint
ALTER TABLE "food_suggestions" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "food_suggestions" DROP COLUMN "username";--> statement-breakpoint
ALTER TABLE "food_suggestions" DROP COLUMN "suggestion";--> statement-breakpoint
ALTER TABLE "food_suggestions" DROP COLUMN "prompt";--> statement-breakpoint
ALTER TABLE "food_suggestions" DROP COLUMN "created_at";