-- Add confirmation_preferences table
CREATE TABLE "confirmation_preferences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "confirmation_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"target_user_id" bigint NOT NULL,
	"require_debt_creation" boolean DEFAULT true,
	"require_debt_payment" boolean DEFAULT true,
	"require_debt_deletion" boolean DEFAULT true,
	"require_debt_completion" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "confirmation_preferences_user_id_target_user_id_unique" UNIQUE("user_id","target_user_id")
);

-- Add foreign key constraints
ALTER TABLE "confirmation_preferences" ADD CONSTRAINT "confirmation_preferences_user_id_tg_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "confirmation_preferences" ADD CONSTRAINT "confirmation_preferences_target_user_id_tg_users_id_fk" FOREIGN KEY ("target_user_id") REFERENCES "public"."tg_users"("id") ON DELETE cascade ON UPDATE no action;